name: Android CI

# Trigger the workflow on push or pull request
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode TALVIEW_PROVIEW_TOKEN
        run: echo TALVIEW_PROVIEW_TOKEN="FAKETOKEN" > ./local.properties

      - name: Clean
        run: ./gradlew clean

      - name: Build
        run: ./gradlew assembleDebug --stacktrace